# Architecture
model: dsc_arch
image_size: 32
layer_config: [32, 64, 128, 256, 512]
num_heads: 8
hidden_dim: 64
expansion: 4

# Dataset
dataset: CIFAR10

# HyperParameters
epochs: 8
batch_size: 8
learning_rate: 0.0001
scheduler: True
num_workers: 1
weighted_loss: False
early_stop_tolerance: 20

# Misc
augment: False