# Architecture
model: dsc_arch
latent_smoothing: True
image_size: 32
hidden_config: [64, 128, 256, 512, 1024]
latent_dim: 4096
kl_weight: 0
lam: 0.0075

# Dataset
dataset: CIFAR10

# HyperParameters
epochs: 50
batch_size: 64
learning_rate: 0.0001
scheduler: True
num_workers: 1
weighted_loss: False
early_stop_tolerance: 10

# Misc
augment: False